# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6eae8a343193f7c023699edb5bce32728a9d0b8ef20c97b702fa8f3bdfd294c399ab2d998d281ed6a82ce1b8501ff081331894a58c69f93963b7ea4b67e64f5c

test:
  secret_key_base: 991e7af0ccb1753873e9eff1bf93c19444f5907696fbed0a4fc229095ecba2fc42783bb23defa6beee91016786f778e11afbf3854a656e370b758390e57aa58e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
